easydocs/urls.py
# D:\Gabriel\Programs\EasyDocs\easydocs\urls.py

from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('users/logout/', views.logout_view, name='users-logout'),
    path('files/', include('files.urls')),
]

files/urls.py
from django.urls import path
from . import views

app_name = 'files'

urlpatterns = [
    path('download/<int:file_id>/', views.download_file, name='download_file'),
    path('pdf-generator/', views.pdf_generator_view, name='pdf_generator'),
    path('create-template/', views.create_template_view, name='create_template'),
    path('fill/<int:template_id>/', views.fill_template_view, name='fill_template'),
    path('files/', views.file_management_view, name='file_management'),
    path('files/create-folder/', views.create_folder_view, name='create_folder'),
    path('files/upload/', views.upload_file_view, name='upload_file'),
    path('files/delete/<int:file_id>/', views.delete_file_view, name='delete_file'),
    path('files/delete-folder/<int:folder_id>/', views.delete_folder_view, name='delete_folder'),
]

templates/base.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <title>EasyDocs</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>

<body>
    <header>
        <nav>
            <a href="{% url 'home' %}">Página inicial</a>
            <a href="{% url 'files:pdf_generator' %}">Gerador de PDF</a>
            <a href="{% url 'files:file_management' %}">Gestão de arquivos</a>
        </nav>
    </header>
    {% block content %}
    <!-- O conteúdo da página vai aqui -->
    {% endblock %}
</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block content %}
    <h2>Bem-vindo!</h2>
    <ul>
        <li><a href="{% url 'files:pdf_generator' %}">Gerar PDF</a></li>
        <li><a href="{% url 'files:file_management' %}">Gerir Pastas e Documentos</a></li>
        <li><a href="/users/logout/">Logout</a></li>
    </ul>
{% endblock %}